// <auto-generated />
using DigimonApp.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigimonApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221030162113_MoreData")]
    partial class MoreData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DigimonApp.Domain.Models.Digimon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Digimons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://digimon.shadowsmith.com/img/agumon.jpg",
                            Level = "Rookie",
                            Name = "Agumon"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://digimon.shadowsmith.com/img/agumon.jpg",
                            Level = "Rookie",
                            Name = "Agumon"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://digimon.shadowsmith.com/img/agumon.jpg",
                            Level = "Rookie",
                            Name = "Agumon"
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://digimon.shadowsmith.com/img/agumon.jpg",
                            Level = "Rookie",
                            Name = "Agumon"
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 12,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 13,
                            Image = "https://digimon.shadowsmith.com/img/agumon.jpg",
                            Level = "Rookie",
                            Name = "Agumon"
                        },
                        new
                        {
                            Id = 14,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 15,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 16,
                            Image = "https://digimon.shadowsmith.com/img/agumon.jpg",
                            Level = "Rookie",
                            Name = "Agumon"
                        },
                        new
                        {
                            Id = 17,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 18,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 19,
                            Image = "https://digimon.shadowsmith.com/img/agumon.jpg",
                            Level = "Rookie",
                            Name = "Agumon"
                        },
                        new
                        {
                            Id = 20,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 21,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 22,
                            Image = "https://digimon.shadowsmith.com/img/agumon.jpg",
                            Level = "Rookie",
                            Name = "Agumon"
                        },
                        new
                        {
                            Id = 23,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        },
                        new
                        {
                            Id = 24,
                            Image = "https://digimon.shadowsmith.com/img/greymon.jpg",
                            Level = "Champion",
                            Name = "Greymon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
